# Server configuration
server:
  port: 5000 #set your port

# App information
info:
  app:
    name: Kotlin API Boilerplate
    version: 1.0
    description: Boilerplate to start an API in Kotlin

# Spring Boot configuration
spring:
  application:
    name: kotlin-api
  # Security configuration
  security:
    user:
      name: admin
      password: admin
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_boilerplate
    username: demo_dev
    password: ${db_password}
  # JPA properties
  jpa:
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 50MB
  # Date properties
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mail:
    host: localhost
    port: 1025
    username: email_username
    password: password
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

# Logger configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5p) [%t] txn[%X{transactionId}] %C{1} [%M] - %m%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5p) [%t] txn[%X{transactionId}] %C{1} [%M] - %m%n"
  level:
    ROOT: warn
    web: info
    com.example.apiboilerplate: info
    org.springframework: info
    org.hibernate: off
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 365  # Keep logs for 1 year

# Actuator
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

boilerplate-env:
  server:
    domain: boilerplate.com
    # Add origins that will be allowed on CORS mapping (separated by comma)
    allowed-origins: http://localhost:8080
  # Authentication related
  authentication:
    should-session-expire: false
    session-expires-in: 1000000     # number of seconds session is valid for after last activity
    session-token-length: 72
  paths:
    public:
      admin-profile-images: ./storage/private/admin/{adminId}/profile_image/
      customer-profile-images: ./storage/private/customer/{customerId}/profile_image/

--- # DEBUG PROFILE

spring:
  config:
    activate:
      on-profile: debug
  jpa:
    show-sql: false
  mail: # be sure to run maildev locally (check scripts/maildev_cheatsheet.sh)
    host: localhost
    port: 1025
    username: maildev_username
    password: password

logging:
  level:
    ROOT: warn
    web: info
    com.example.apiboilerplate: debug
    org.springframework: info
    org.hibernate: off

--- # DEV PROFILE

spring:
  config:
    activate:
      on-profile: dev

--- # PROD PROFILE

spring:
  config:
    activate:
      on-profile: prod
